[sources.filesystem.credentials]
client_email=""
private_key=""
project_id="ahfc-data-tutorials"

[destination.bigquery]
location = "US"
[destination.bigquery.credentials]
client_email=""
private_key=""
project_id=""
