[project]
name = "cloudrun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.8"
dependencies = [
    "dlt[bigquery,filesystem,gs]>=1.10.0",
    "duckdb>=1.2.2",
]
